### ISSUE TITLE
Exceptions parsing proxied response causes error: Can't set headers after they are sent

### ISSUE THREAD

**Issue by jrullmann** [villadora/express-http-proxy#104]
If an exception occurs while parsing the proxied response, a 'Can't set headers after they are sent' error is thrown. This also causes my node server to exit.

The stack trace looks like this:
```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (/Users/jenniferrullmann/code/proj/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/Users/jenniferrullmann/code/proj/node_modules/express/lib/response.js:176:10)
    at /Users/jenniferrullmann/code/proj/node_modules/express-http-proxy/index.js:147:21
    at app.use.proxy.intercept (/Users/jenniferrullmann/code/proj/server.js:47:7)
    at IncomingMessage.<anonymous> (/Users/jenniferrullmann/code/proj/node_modules/express-http-proxy/index.js:113:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
```

If I modify [https://github.com/villadora/express-http-proxy/blob/master/index.js#L120](this) code to check if the headers have been set:

```
if (!res.headersSent) {
    res.send(rspData);
}
```

then I can see that an error occured parsing the proxied response body:

```
Error: Parse Error
    at Error (native)
    at TLSSocket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
```

Here's a [SO question](http://stackoverflow.com/questions/7042340/node-js-error-cant-set-headers-after-they-are-sent) that goes into detail about why this happens. It appears that something upstream of `express-http-proxy` is calling `writeHead` earlier than usual because of this parsing error.

For now, I'm working around the problem by intercepting the response in my server, so my node server stays up and I can see the root exception.

```
  // Proxy requests to the upstream API
  app.use('/api', proxy(upstream_api_url, {
    intercept: function(rsp, data, req, res, callback) {
      callback(null, data, res.headersSent);
    }
  }))
```

Seems like adding a check for `headersSent` before calling `res.send` would fix the issue, and I could remove the silly workaround.

**Comment by monkpow** [comment]
Thanks for a detailed issue report.  I'll look into this this week.

**Comment by monkpow** [comment]
Thanks @jrullmann!
