### ISSUE TITLE
Unhandled promise rejection: Error: request aborted

### ISSUE THREAD

**Issue by martinzuern** [villadora/express-http-proxy#224]
I regularly receive the following issue on GET requests: `(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 35): Error: request aborted`. This only happens since the update to v1.0.

```
Error: request aborted
at IncomingMessage.onAborted (/usr/src/app/node_modules/raw-body/index.js:269:10)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at IncomingMessage.wrapped (/usr/src/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
at IncomingMessage.wrappedEmit [as emit] (/usr/src/app/node_modules/newrelic/lib/transaction/tracer/index.js:221:46)
at abortIncoming (_http_server.js:283:11)
at Socket.socketOnEnd (_http_server.js:436:7)
at emitNone (events.js:91:20)
at Socket.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
```
(Logs from a production machine, sorry about the newrelic spam)

**Comment by monkpow** [comment]
@martinzuern Thanks for the ticket.    Can you give me a little more information so that I might be able to reproduce the issue at my end.   The current test cases I'm running don't trigger this issue, but I'd like to test and repair it.

Thanks!

**Comment by martinzuern** [comment]
It's pretty hard to reproduce – the issue occurred on my end when hosting the node app on AWS ECS and running a loadtest from BlazeMeter.com. Nevertheless, after some more testing I'm convinced that this issue is more related to raw-body than to this package. Thanks for your quick response!

**Comment by monkpow** [comment]
I reviewed the code and it looks like there are some quirks in how timeouts and aborts are handled (or not handled),  so I think you have identified an issue in this lib.   I'll try to construct some cases that expose this issue.
