### ISSUE TITLE
Proxy cannot handle large files

### ISSUE THREAD

**Issue by jdiehl** [villadora/express-http-proxy#27]
Thanks for the great Express add-on!

When trying to send a large file through the proxy (more than 1 MB), an error event is thrown:

```
Error: request entity too large
at makeError (.../node_modules/express-http-proxy/node_modules/raw-body/index.js:184:15)
at module.exports (.../node_modules/express-http-proxy/node_modules/raw-body/index.js:40:15)
at handleProxy (.../node_modules/express-http-proxy/index.js:54:5)
at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:82:5)
at trim_prefix (.../node_modules/express/lib/router/index.js:302:13)
at .../node_modules/express/lib/router/index.js:270:7
at Function.proto.process_params (.../node_modules/express/lib/router/index.js:321:12)
at next (.../node_modules/express/lib/router/index.js:261:10)
at serveStatic (.../node_modules/express/node_modules/serve-static/index.js:59:14)
at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:82:5)
```

Could you use streams instead of reading the entire body into a buffer?

**Comment by Onigam** [comment]
You can specify the limit in the options:

```
exports.proxy = proxy(
	config.API_BASE_URL, {
		limit: "120mb",
		forwardPath: ...
	}
);
```

**Comment by jdiehl** [comment]
Thanks for the pointer - that will solve it for me for now.

It feels a little wrong though... A proxy should not load the entire request into a buffer and then send that buffer to the target. Instead the proxy should forward the stream as data arrives, making the process faster and less memory intensive. Do you think this would be possible to implement?
