### ISSUE TITLE
Invalid host header for HTTPS proxy request

### ISSUE THREAD

**Issue by bitsal** [villadora/express-http-proxy#296]
**Version:**  1.0.7

**Case:**
I have an app running on `http://localhost:3000/api/data` using a proxy (configured with this library) to the api server like `https://domain.name/api/data`. By default, all headers are copied (except `content-length` as I mentioned [here](https://github.com/villadora/express-http-proxy/issues/221#issuecomment-343886520)) and `host` header as well (it is `localhost:3000` of course).

I encounter an error like this:
```
Error: Hostname/IP doesn't match certificate's altnames: "Host: localhost. is not in the cert's altnames: DNS:domain.name"
    at Object.checkServerIdentity (tls.js:222:17)
    at TLSSocket.<anonymous> (_tls_wrap.js:1109:29)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)

```

**My Fix:**
To fix it I have to add this:
```
devServer.use('/api', httpProxy(apiServerUrl, {
...
proxyReqOptDecorator: function (proxyReqOpts, srcReq) {
    for (var header in srcReq.headers) { // keep headers as is due to some headers are missed
        proxyReqOpts.headers[header] = srcReq.headers[header];
    }
    proxyReqOpts.headers['host'] = ''; // probably, the best option is to set right domain name instead of empty value

    return proxyReqOpts;
}
...
}));
```

My thought is this library should take care of `host` header as a default behavior to avoid such sort of code copy-pasting from one project to another project.

**Comment by monkpow** [comment]
see option

```
preserveHostHdr

You can copy the host HTTP header to the proxied express server using the preserveHostHdr option.

app.use('/proxy', proxy('www.google.com', {
  preserveHostHdr: true
}));
```

Does this solve your problem outright?

**Comment by bitsal** [comment]
This option was there from the beginning.

**Comment by monkpow** [comment]
Agree, but I can't tell from this end if the existing option solves your problem or not.      It seems like you might be asking for a 'spoof' host header instead?

**Comment by bitsal** [comment]
Yea, otherwise I have to make it empty or override it by the host of a proxied server (it is only in case of HTTPS).

**Comment by bitsal** [comment]
I find myself thinking about making this option `false` :). I will check it tomorrow.

**Comment by bitsal** [comment]
Checked. It didn't help.
```
preserveHostHdr: false
```

`true` was before.

**Comment by monkpow** [comment]
So when you say you think the library should take care of this, what would you like to happen?   It seems in this case you'd like to set a custom header on the proxyReq without having to be responsible for all the headers.   Am I on the same page with you?

**Comment by monkpow** [comment]
I think you can simplify your example like so

```
devServer.use('/api', httpProxy(apiServerUrl, {
   proxyReqOptDecorator: function (proxyReqOpts, srcReq) {
       proxyReqOpts.headers['host'] = ''; /
       return proxyReqOpts;
   }
}));
```

This feels pretty lightweight to me as far as setting the host header to any value you want it to be.

I think the other chunk you're working with is for covering a different missing header?   Perhaps content-length?      

Let me know what you think here.   I feel pretty about this as a solution to your host header request, and I'll address the content-length header on your other thread.

Any other headers you feel are missing?

**Comment by bitsal** [comment]
Not custom header, well-known `Host` header. I would like to use this library and proxy HTTPS servers without copy-pasting code like above (where I set `Host` header to empty string).

It means with default configs my proxy can't work with HTTPS (what is a common approach to use HTTPS, except cases when a proxied server is hidden in private network or nobody cares about keeping it secure).

Yes, copying source request headers is related only to `content-length` missed header.

It is not a huge problem to add this part of the code to my config. By this ticket, I wanted to say that I think this lib should cover HTTPS **by default** without extra code changes due to HTTPS is not a rare use case.

**Comment by bitsal** [comment]
I can contribute if we are on the same page that it is really needed to be a default behavior.

**Comment by monkpow** [comment]
Ok, so I appreciate the conversation, and I like where is going.    My question about custom is not about if ```Host``` is a custom header, but it seems to me that "" (empty string) is a custom local value/solution.     Are you suggesting that by default, host be set to "" (empty string) for all https proxies?     I'm a little unsure that this is a globally relevant solution, but would like to hear your thoughts, or clarify the question if I'm misunderstanding.

**Comment by bitsal** [comment]
Oh, of course, no. It should be set to a real proxied server host.

**Comment by monkpow** [comment]
Ok, cool.     Do you have an idea of how the library would intuit or derive a real proxied server host?

By the way, I appreciate the offer to contribute;  I tend to not change the default behavior on minor or patch releases, so my current POV is that the feature be opt-in until the next major release.

**Comment by bitsal** [comment]
e.g.
we have a configuration like this
```
app.use('/api', proxy('https://api.server.com', {
  ...
}));
```
`https://api.server.com` should be parsed and 'Host' header is set based on it.

**Comment by monkpow** [comment]
Interesting.  Ok, thank you for the several steps of clarifying.    Let me chew on this a little bit;   I see what you're saying and I find this interesting;  I don't currently agree it should be the default option, but It seems reasonable to make it easy for an author flip a bit to make this happen.
