### ISSUE TITLE
Get 404 Not found error

### ISSUE THREAD

**Issue by sharebooks** [villadora/express-http-proxy#319]
Create a express app and copy the following code, then got 404 error.

var proxy = require('express-http-proxy');
var app = require('express')();
 
app.use('/proxy', proxy('www.google.com'));

    at Layer.handle [as handle_request] (/AAA/gearup-proxy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/AAA/gearup-proxy/node_modules/express/lib/router/index.js:317:13)
    at /AAA/gearup-proxy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/AAA/gearup-proxy/node_modules/express/lib/router/index.js:335:12)
    at next (/AAA/gearup-proxy/node_modules/express/lib/router/index.js:275:10)
    at /AAA/gearup-proxy/node_modules/express/lib/router/index.js:635:15
    at next (/AAA/gearup-proxy/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/AAA/gearup-proxy/node_modules/express/lib/router/index.js:174:3)
    at router (/AAA/gearup-proxy/node_modules/express/lib/router/index.js:47:12)

**Comment by Nina0408** [comment]
Please try put below code at the end of your index.js.

app.use('/proxy', proxy('www.google.com'));

**Comment by monkpow** [comment]
I get 
```
> res.text
'<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world\'s information, including webpages, images, videos and more. Google...'
```
