### ISSUE TITLE
Self Signed Cert issue while making HTTPS request from HTTP (proxy)

### ISSUE THREAD

**Issue by radloori** [villadora/express-http-proxy#324]
I am running client app on http and proxy on http, I am calling a https url from proxy server. I am getting 
self signed certificate error even after using https: true [as per docs]
```
const baseUrl2 = "https://localhost:5002";
var app = express();
app.use('/api/settings', proxy(baseUrl2, {
  https: true,
  //
  //
}
```
output:
Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1042:34)
    at TLSSocket.emit (events.js:159:13)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)

**Comment by codegagan** [comment]
Getting the same error, is there any workaround ?

**Comment by gstroup** [comment]
The easy (but insecure) workaround is to add this environment variable:

`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request

**Comment by codegagan** [comment]
Found a way without setting it to environment level. Example below

```
app.use('/', proxy('internalhost.example.com', {
  proxyReqOptDecorator: function(proxyReqOpts, originalReq) {
    proxyReqOpts.rejectUnauthorized = false
    return proxyReqOpts;
  }
})
```
