### ISSUE TITLE
Node 4 Support

### ISSUE THREAD

**Issue by patrickhousley** [villadora/express-http-proxy#35]
I am getting the below error when proxying to an HTTPS address and only when using Node 4:

```
Error: write EPROTO
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at WriteWrap.afterWrite (net.js:763:14)
```

If I switch back to node 0.12, everything works fine. This may very well be an issue on my end but it is strange this only happens when I change to Node 4. Any ideas?

**Comment by patrickhousley** [comment]
Found issue was due to Node 4 dropping support for RC4 ciphers out of the box. We had to enabled RC4 cipher support to get this working again.
